# Tasks package initialization
from .network_monitoring_tasks import create_network_data_collection_task, create_metrics_analysis_task, create_real_time_metrics_summary_task
from .anomaly_detection_tasks import create_anomaly_detection_task, create_diagnostic_analysis_task, create_impact_assessment_task
from .optimization_tasks import create_optimization_strategy_task, create_self_healing_recommendations_task, create_parameter_tuning_task
from .user_experience_tasks import create_ux_impact_analysis_task, create_predictive_issue_prevention_task, create_user_adaptive_optimization_task
from .reporting_tasks import create_technical_report_task, create_performance_visualization_task, create_executive_summary_task
